<?php

namespace Modules\Mbkm\Controllers;

use App\Http\Controllers\Controller;
use App\Support\Traits\HasApiResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Modules\Assessment\Services\GradeCalculationService;
use Modules\Mbkm\Models\MbkmActivity;
use Modules\Mbkm\Models\MbkmAssessment;
use Modules\Mbkm\Models\MbkmAssessmentComponent;
use Modules\Mbkm\Models\MbkmAttendance;
use Modules\Mbkm\Models\MbkmLogbook;
use Modules\Mbkm\Models\MbkmParticipant;
use Modules\Mbkm\Models\MbkmRecognition;

class MbkmParticipantController extends Controller
{
    use HasApiResponse;
    public function index(Request $request): JsonResponse { $q=MbkmParticipant::with(['student.studyProgram','program.type','application','recognition']); if($request->user()->hasRole('mahasiswa')) $q->where('student_id',$request->user()->student?->id ?? 0); return $this->paginatedResponse($q->latest()->paginate((int)$request->query('per_page',15)), 'Daftar peserta MBKM berhasil dimuat.'); }
    public function updateStatus(Request $request, MbkmParticipant $mbkmParticipant): JsonResponse { $data=$request->validate(['status'=>['required','in:accepted,confirmed,ongoing,completed,withdrawn,terminated'],'notes'=>['nullable','string']]); if($data['status']==='ongoing'&&!$mbkmParticipant->started_at)$data['started_at']=now(); if($data['status']==='completed')$data['completed_at']=now(); $mbkmParticipant->update($data); return $this->successResponse($mbkmParticipant->fresh(),'Status peserta berhasil diperbarui.'); }
    public function activities(Request $request, MbkmParticipant $mbkmParticipant): JsonResponse { $this->assertOwnerOrReviewer($request,$mbkmParticipant); return $this->successResponse($mbkmParticipant->activities()->latest()->get(),'Aktivitas MBKM berhasil dimuat.'); }
    public function storeActivity(Request $request, MbkmParticipant $mbkmParticipant): JsonResponse { $this->assertOwnerOrReviewer($request,$mbkmParticipant); $data=$request->validate(['title'=>['required','string'],'description'=>['nullable','string'],'planned_start'=>['nullable','date'],'planned_end'=>['nullable','date','after_or_equal:planned_start'],'status'=>['required','in:planned,ongoing,completed,cancelled']]); return $this->successResponse($mbkmParticipant->activities()->create($data),'Aktivitas MBKM berhasil dibuat.',201); }
    public function storeLogbook(Request $request, MbkmParticipant $mbkmParticipant): JsonResponse { $this->assertOwnerOrReviewer($request,$mbkmParticipant); $data=$request->validate(['activity_id'=>['nullable','exists:mbkm_activities,id'],'activity_date'=>['required','date'],'description'=>['required','string'],'hours'=>['nullable','numeric','min:0']]); if(isset($data['activity_id'])&&!$mbkmParticipant->activities()->whereKey($data['activity_id'])->exists()) throw ValidationException::withMessages(['activity_id'=>['Aktivitas bukan milik peserta.']]); return $this->successResponse($mbkmParticipant->logbooks()->create($data),'Logbook berhasil dikirim.',201); }
    public function reviewLogbook(Request $request, MbkmLogbook $mbkmLogbook): JsonResponse { $data=$request->validate(['status'=>['required','in:approved,rejected'],'review_notes'=>['nullable','string']]); $mbkmLogbook->update($data+['reviewed_by'=>$request->user()->id,'reviewed_at'=>now()]); return $this->successResponse($mbkmLogbook->fresh(),'Logbook berhasil ditinjau.'); }
    public function attendance(Request $request, MbkmParticipant $mbkmParticipant): JsonResponse { $this->assertOwnerOrReviewer($request,$mbkmParticipant); return $this->successResponse(MbkmAttendance::where('participant_id',$mbkmParticipant->id)->orderByDesc('attendance_date')->get(),'Kehadiran berhasil dimuat.'); }
    public function storeAttendance(Request $request, MbkmParticipant $mbkmParticipant): JsonResponse { $this->assertOwnerOrReviewer($request,$mbkmParticipant); $data=$request->validate(['attendance_date'=>['required','date'],'status'=>['required','in:present,late,excused,absent'],'hours'=>['nullable','numeric','min:0'],'notes'=>['nullable','string']]); $row=MbkmAttendance::updateOrCreate(['participant_id'=>$mbkmParticipant->id,'attendance_date'=>$data['attendance_date']],$data); return $this->successResponse($row,'Kehadiran berhasil disimpan.'); }
    public function storeAssessment(Request $request, MbkmParticipant $mbkmParticipant): JsonResponse { $data=$request->validate(['component_id'=>['required','exists:mbkm_assessment_components,id'],'score'=>['required','numeric','min:0'],'notes'=>['nullable','string']]); $component=MbkmAssessmentComponent::whereKey($data['component_id'])->where('program_id',$mbkmParticipant->program_id)->firstOrFail(); if($data['score']>$component->maximum_score)throw ValidationException::withMessages(['score'=>['Nilai melampaui nilai maksimum komponen.']]); $score=MbkmAssessment::updateOrCreate(['participant_id'=>$mbkmParticipant->id,'component_id'=>$component->id],$data+['assessed_by'=>$request->user()->id]); return $this->successResponse($score,'Penilaian MBKM berhasil disimpan.'); }
    public function createRecognition(Request $request, MbkmParticipant $mbkmParticipant, GradeCalculationService $grades): JsonResponse { if($mbkmParticipant->status!=='completed')throw ValidationException::withMessages(['participant'=>['Rekognisi hanya untuk peserta yang telah selesai.']]); $data=$request->validate(['semester_id'=>['required','exists:semesters,id'],'courses'=>['required','array','min:1'],'courses.*.course_id'=>['required','distinct','exists:courses,id'],'courses.*.credits'=>['required','integer','min:1'],'courses.*.score'=>['nullable','numeric','between:0,100']]); $total=array_sum(array_column($data['courses'],'credits')); if($total>$mbkmParticipant->program->credit_limit)throw ValidationException::withMessages(['courses'=>['Total konversi melebihi batas SKS program.']]); $recognition=DB::transaction(function()use($mbkmParticipant,$data,$grades,$total){$recognition=MbkmRecognition::updateOrCreate(['participant_id'=>$mbkmParticipant->id],['semester_id'=>$data['semester_id'],'total_credits'=>$total,'status'=>'submitted']);$recognition->courses()->delete();foreach($data['courses'] as $course){$conversion=isset($course['score'])?$grades->convertScoreToGrade((float)$course['score']):[];$recognition->courses()->create($course+['letter_grade'=>$conversion['letter_grade']??null]);}return $recognition;}); return $this->successResponse($recognition->load('courses'),'Pengajuan rekognisi berhasil dibuat.'); }
    private function assertOwnerOrReviewer(Request $request, MbkmParticipant $participant): void { $user=$request->user(); if($user->hasRole('mahasiswa')) { if($user->student?->id!==$participant->student_id) abort(403); return; } if(!$user->hasPermissionTo('mbkm.review') && !$user->hasPermissionTo('mbkm.manage')) abort(403); }
}
